(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"ChiralQCD",
  Authors -> {"L. Mason"},
  Date -> "2019",
  Institutions -> {"University of Johannesburg"},
  Emails -> {"lara.mason@live.com"},
  Version -> "1"};

FR$ClassesTranslation={A -> V[1], Z -> V[2], W -> V[3], G -> V[4], pi -> S[1], pi0 -> S[2], Ka0 -> S[3], Kap -> S[4], eta -> S[5], etap -> S[6]};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

S[1] == {
    SelfConjugate -> False,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> Mpi,
    Indices -> {},
    PropagatorLabel -> "pi" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Mpi0,
    Indices -> {Index[SU2W]},
    PropagatorLabel -> "pi0" },

S[3] == {
    SelfConjugate -> False,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MKa0,
    Indices -> {},
    PropagatorLabel -> "Ka0" },

S[4] == {
    SelfConjugate -> False,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MKap,
    Indices -> {},
    PropagatorLabel -> "Kap" },

S[5] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Meta,
    Indices -> {},
    PropagatorLabel -> "eta" },

S[6] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Metap,
    Indices -> {},
    PropagatorLabel -> "etap" }
}


(*        Definitions       *)

GaugeXi[ S[2] ] = GaugeXi[S[12]];
GaugeXi[ S[5] ] = GaugeXi[S[3]];
GaugeXi[ S[6] ] = GaugeXi[S[4]];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Mpi[ ___ ] := Mpi;
Mpi0[ ___ ] := Mpi0;
MKa0[ ___ ] := MKa0;
MKap[ ___ ] := MKap;
Meta[ ___ ] := Meta;
Metap[ ___ ] := Metap;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ S[2, {__}] ] := TheLabel[S[2]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(((2*I)/3)*(Ms + Mup))/fp^2, 0}},

C[ S[3] , -S[3] , S[4] , -S[4] ] == {{((I/6)*(Ms + Mup))/fp^2, 0}},

C[ S[4] , S[4] , -S[4] , -S[4] ] == {{((I/6)*(Ms + Mup))/fp^2, 0}},

C[ S[3] , -S[3] , S[1] , -S[1] ] == {{((I/6)*(Ms + 3*Mup))/fp^2, 0}},

C[ S[4] , -S[4] , S[1] , -S[1] ] == {{((I/12)*(Ms + 3*Mup))/fp^2, 0}},

C[ S[1] , S[1] , -S[1] , -S[1] ] == {{(((4*I)/3)*Mup)/fp^2, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
};

