(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"ChiralQCD",
  Authors -> {"L. Mason"},
  Date -> "2019",
  Institutions -> {"University of Johannesburg"},
  Emails -> {"lara.mason@live.com"},
  Version -> "1"};

FR$ClassesTranslation={A -> V[1], Z -> V[2], W -> V[3], G -> V[4], pip -> S[1], pim -> S[2], pi0 -> S[3], Ka0 -> S[4], Kap -> S[5], eta -> S[6], etap -> S[7]};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Mpip,
    Indices -> {},
    PropagatorLabel -> "pip" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Mpim,
    Indices -> {},
    PropagatorLabel -> "pim" },

S[3] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Mpi0,
    Indices -> {},
    PropagatorLabel -> "pi0" },

S[4] == {
    SelfConjugate -> False,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MKa0,
    Indices -> {},
    PropagatorLabel -> "Ka0" },

S[5] == {
    SelfConjugate -> False,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MKap,
    Indices -> {},
    PropagatorLabel -> "Kap" },

S[6] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Meta,
    Indices -> {},
    PropagatorLabel -> "eta" },

S[7] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Metap,
    Indices -> {},
    PropagatorLabel -> "etap" }
}


(*        Definitions       *)

GaugeXi[ S[6] ] = GaugeXi[S[3]];
GaugeXi[ S[7] ] = GaugeXi[S[4]];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Mpip[ ___ ] := Mpip;
Mpim[ ___ ] := Mpim;
Mpi0[ ___ ] := Mpi0;
MKa0[ ___ ] := MKa0;
MKap[ ___ ] := MKap;
Meta[ ___ ] := Meta;
Metap[ ___ ] := Metap;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[4] , S[4] , -S[4] , -S[4] ] == {{(((2*I)/3)*(Md + Ms))/fp^2, 0}},

C[ S[4] , -S[4] , S[5] , -S[5] ] == {{((I/12)*(Md + 2*Ms + Mup))/fp^2, 0}},

C[ S[5] , S[5] , -S[5] , -S[5] ] == {{((I/6)*(Ms + Mup))/fp^2, 0}},

C[ S[4] , -S[4] , S[3] , S[3] ] == {{((I/12)*(3*Md + Ms))/fp^2, 0}},

C[ S[5] , -S[5] , S[3] , S[3] ] == {{((I/24)*(Ms + 3*Mup))/fp^2, 0}},

C[ S[3] , S[3] , S[3] , S[3] ] == {{((I/4)*(Md + Mup))/fp^2, 0}},

C[ -S[4] , S[5] , S[3] , S[2] ] == {{((-I/24)*(Md - Mup))/(Sqrt[2]*fp^2), 0}},

C[ S[4] , -S[5] , S[3] , S[1] ] == {{((-I/6)*(Md - Mup))/(Sqrt[2]*fp^2), 0}},

C[ S[4] , -S[4] , S[2] , S[1] ] == {{((I/6)*(2*Md + Ms + Mup))/fp^2, 0}},

C[ S[5] , -S[5] , S[2] , S[1] ] == {{((I/12)*(Md + Ms + 2*Mup))/fp^2, 0}},

C[ S[3] , S[3] , S[2] , S[1] ] == {{((I/6)*(Md + Mup))/fp^2, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(((2*I)/3)*(Md + Mup))/fp^2, 0}},

C[ S[6] , S[4] , -S[4] , S[3] ] == {{((-I/12)*(Md - Ms)*Cos[Th])/(Sqrt[3]*fp^2), 0}},

C[ S[6] , S[5] , -S[5] , S[3] ] == {{((-I/24)*(Ms - Mup)*Cos[Th])/(Sqrt[3]*fp^2), 0}},

C[ S[6] , S[3] , S[3] , S[3] ] == {{((-I/4)*(Md - Mup)*Cos[Th])/(Sqrt[3]*fp^2), 0}},

C[ S[6] , -S[4] , S[5] , S[2] ] == {{((I/24)*(Md - 2*Ms + Mup)*Cos[Th])/(Sqrt[6]*fp^2), 0}},

C[ S[6] , S[4] , -S[5] , S[1] ] == {{((I/6)*(Md - 2*Ms + Mup)*Cos[Th])/(Sqrt[6]*fp^2), 0}},

C[ S[6] , S[3] , S[2] , S[1] ] == {{((-I/6)*(Md - Mup)*Cos[Th])/(Sqrt[3]*fp^2), 0}},

C[ S[6] , S[6] , S[4] , -S[4] ] == {{((I/12)*(Md + 3*Ms)*Cos[Th]^2)/fp^2, 0}},

C[ S[6] , S[6] , S[5] , -S[5] ] == {{((I/24)*(3*Ms + Mup)*Cos[Th]^2)/fp^2, 0}},

C[ S[6] , S[6] , S[3] , S[3] ] == {{((I/12)*(Md + Mup)*Cos[Th]^2)/fp^2, 0}},

C[ S[6] , S[6] , S[2] , S[1] ] == {{((I/6)*(Md + Mup)*Cos[Th]^2)/fp^2, 0}},

C[ S[6] , S[6] , S[6] , S[3] ] == {{((-I/12)*(Md - Mup)*Cos[Th]^3)/(Sqrt[3]*fp^2), 0}},

C[ S[6] , S[6] , S[6] , S[6] ] == {{((I/36)*(Md + 16*Ms + Mup)*Cos[Th]^4)/fp^2, 0}},

C[ S[7] , S[4] , -S[4] , S[3] ] == {{((-I/12)*(Md - Ms)*Sin[Th])/(Sqrt[3]*fp^2), 0}},

C[ S[7] , S[5] , -S[5] , S[3] ] == {{((-I/24)*(Ms - Mup)*Sin[Th])/(Sqrt[3]*fp^2), 0}},

C[ S[7] , S[3] , S[3] , S[3] ] == {{((-I/4)*(Md - Mup)*Sin[Th])/(Sqrt[3]*fp^2), 0}},

C[ S[7] , -S[4] , S[5] , S[2] ] == {{((I/24)*(Md - 2*Ms + Mup)*Sin[Th])/(Sqrt[6]*fp^2), 0}},

C[ S[7] , S[4] , -S[5] , S[1] ] == {{((I/6)*(Md - 2*Ms + Mup)*Sin[Th])/(Sqrt[6]*fp^2), 0}},

C[ S[7] , S[3] , S[2] , S[1] ] == {{((-I/6)*(Md - Mup)*Sin[Th])/(Sqrt[3]*fp^2), 0}},

C[ S[6] , S[7] , S[4] , -S[4] ] == {{((I/24)*(Md + 3*Ms)*Sin[2*Th])/fp^2, 0}},

C[ S[6] , S[7] , S[5] , -S[5] ] == {{((I/48)*(3*Ms + Mup)*Sin[2*Th])/fp^2, 0}},

C[ S[6] , S[7] , S[3] , S[3] ] == {{((I/24)*(Md + Mup)*Sin[2*Th])/fp^2, 0}},

C[ S[6] , S[7] , S[2] , S[1] ] == {{((I/6)*(Md + Mup)*Cos[Th]*Sin[Th])/fp^2, 0}},

C[ S[6] , S[6] , S[7] , S[3] ] == {{((-I/12)*(Md - Mup)*Cos[Th]^2*Sin[Th])/(Sqrt[3]*fp^2), 0}},

C[ S[6] , S[6] , S[6] , S[7] ] == {{((I/36)*(Md + 16*Ms + Mup)*Cos[Th]^3*Sin[Th])/fp^2, 0}},

C[ S[7] , S[7] , S[4] , -S[4] ] == {{((I/12)*(Md + 3*Ms)*Sin[Th]^2)/fp^2, 0}},

C[ S[7] , S[7] , S[5] , -S[5] ] == {{((I/24)*(3*Ms + Mup)*Sin[Th]^2)/fp^2, 0}},

C[ S[7] , S[7] , S[3] , S[3] ] == {{((I/12)*(Md + Mup)*Sin[Th]^2)/fp^2, 0}},

C[ S[7] , S[7] , S[2] , S[1] ] == {{((I/6)*(Md + Mup)*Sin[Th]^2)/fp^2, 0}},

C[ S[6] , S[7] , S[7] , S[3] ] == {{((-I/12)*(Md - Mup)*Cos[Th]*Sin[Th]^2)/(Sqrt[3]*fp^2), 0}},

C[ S[6] , S[6] , S[7] , S[7] ] == {{((I/144)*(Md + 16*Ms + Mup)*Sin[2*Th]^2)/fp^2, 0}},

C[ S[7] , S[7] , S[7] , S[3] ] == {{((-I/12)*(Md - Mup)*Sin[Th]^3)/(Sqrt[3]*fp^2), 0}},

C[ S[6] , S[7] , S[7] , S[7] ] == {{((I/36)*(Md + 16*Ms + Mup)*Cos[Th]*Sin[Th]^3)/fp^2, 0}},

C[ S[7] , S[7] , S[7] , S[7] ] == {{((I/36)*(Md + 16*Ms + Mup)*Sin[Th]^4)/fp^2, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
};

